language: node_js
node_js:
  - "10"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.projectKey=guillercp93_calculatorNodeJS -Dsonar.organization=guillercp93-github -Dsonar.sources=./app -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -X
